[package]
name = "lang_guild"
version = "0.1.0"
authors = ["Kyle <kyle.mcfar1291@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
reqwest = "*"
net = "*"
select = "*"
error-chain = "*"
url = "*"
regex = "*"
